name: Build, push, and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: cr-hn-1.bizflycloud.vn
          name: cr-hn-1.bizflycloud.vn/cecd854937c8421b81d1d73789acad52/techblog:latest
          username: ${{ secrets.USER_CLOUD }}
          password: ${{ secrets.PASS }}

  deploy:
    name: Deploy to K8S
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        name: Deploy
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment python-example

