name: Build, push, and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: cr-hn-1.bizflycloud.vn
          name: cr-hn-1.bizflycloud.vn/cecd854937c8421b81d1d73789acad52/techblog:${{ steps.vars.outputs.tag }}
          username: ${{ secrets.USER_CLOUD }}
          password: ${{ secrets.PASS }}

  deploy:
    name: Deploy to K8S
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        name: Deploy
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/python-example python-example=python-example:${{ steps.vars.outputs.tag }}

